###
@host = http://localhost:3000
### Post
POST {{host}}/users
Content-Type: application/json

{
    "name": "luis ",
    "email": "is715592@iteso.mx",
    "password": "4321",
    "id":1
}

### GET 1
GET {{host}}/users
Content-Type: application/json

### DELETE
DELETE {{host}}/users:1
Content-Type: application/json

### GET 2
GET {{host}}/users:1
Content-Type: application/json

###Post LogIn con Token
POST {{host}}/users
Content-Type: application/json
{
    "name": "Juan Pablo",
    "email": "is715592@iteso.mx",
    "password": "4321",
    "id":1
}


